export const UI_CONSTANTS = {
  APP: {
    TITLE: 'Digital Asset Management',
    NAME: 'DAM Platform',
  },
  AUTH: {
    LOGIN_TITLE: 'Login to DAM Platform',
    REGISTER_TITLE: 'Create Account',
    EMAIL_LABEL: 'Email',
    PASSWORD_LABEL: 'Password',
    FIRST_NAME_LABEL: 'First Name',
    LAST_NAME_LABEL: 'Last Name',
    LOGIN_BUTTON: 'Login',
    REGISTER_BUTTON: 'Register',
    LOGOUT_BUTTON: 'Logout',
    INVALID_CREDENTIALS: 'Invalid email or password',
    REGISTRATION_SUCCESS: 'Account created successfully',
    LOGIN_SUCCESS: 'Logged in successfully',
  },
  UPLOAD: {
    TITLE: 'Upload Assets',
    DROP_ZONE_ACTIVE: 'Drop the file here...',
    DROP_ZONE_INACTIVE: 'Drag & drop a file here, or click to select',
    TAGS_LABEL: 'Tags (comma-separated)',
    TAGS_PLACEHOLDER: 'design, logo, branding',
    DESCRIPTION_LABEL: 'Description',
    DESCRIPTION_PLACEHOLDER: 'Add a description...',
    UPLOAD_BUTTON: 'Upload',
    UPLOADING_MESSAGE: 'Uploading...',
    UPLOAD_SUCCESS: 'Upload successful!',
    UPLOAD_FAILED: 'Upload failed. Please try again.',
  },
  ASSETS: {
    TITLE: 'Your Assets',
    LOADING: 'Loading assets...',
    NO_ASSETS: 'No assets found',
    DELETE_BUTTON: 'Delete',
    DOWNLOAD_BUTTON: 'Download',
    VIEW_BUTTON: 'View',
    EDIT_BUTTON: 'Edit',
    DELETE_CONFIRM: 'Are you sure you want to delete this asset?',
    DELETE_SUCCESS: 'Asset deleted successfully',
    DELETE_FAILED: 'Failed to delete asset',
  },
  COLLECTIONS: {
    TITLE: 'Collections',
    CREATE_BUTTON: 'Create Collection',
    ADD_TO_COLLECTION: 'Add to Collection',
    REMOVE_FROM_COLLECTION: 'Remove from Collection',
    NAME_LABEL: 'Collection Name',
    DESCRIPTION_LABEL: 'Description',
    PUBLIC_LABEL: 'Make Public',
    CREATE_SUCCESS: 'Collection created successfully',
    CREATE_FAILED: 'Failed to create collection',
  },
  SEARCH: {
    PLACEHOLDER: 'Search assets...',
    NO_RESULTS: 'No results found',
    FILTER_BY_TYPE: 'Filter by Type',
    FILTER_BY_STATUS: 'Filter by Status',
    FILTER_BY_DATE: 'Filter by Date',
    CLEAR_FILTERS: 'Clear Filters',
  },
  COMMON: {
    SAVE: 'Save',
    CANCEL: 'Cancel',
    CONFIRM: 'Confirm',
    CLOSE: 'Close',
    LOADING: 'Loading...',
    ERROR: 'An error occurred',
    SUCCESS: 'Success',
    BACK: 'Back',
    NEXT: 'Next',
    SUBMIT: 'Submit',
  },
  ERRORS: {
    GENERIC: 'Something went wrong. Please try again.',
    NETWORK: 'Network error. Please check your connection.',
    UNAUTHORIZED: 'You are not authorized to perform this action.',
    NOT_FOUND: 'Resource not found.',
    VALIDATION: 'Please check your input and try again.',
  },
} as const;
